import CoreServices
import Foundation
import TwistKit

/// Finds the words no established English dictionary defines.
///
/// The premise holds up under measurement: a word absent from every real dictionary is one
/// nobody will miss. Against the built lexicon it removes 60 board targets — almost all of them
/// surnames (`benes`, `davies`, `granger`, `hatcher`, `shawn`, `silva`) that reached the board
/// through obscure WordNet senses — and roughly 3,900 rare entries of the `abamp`, `abfarad`,
/// `abohm`, `abvolt` variety.
///
/// The result is written to `undefined.txt` and committed, rather than consulted during every
/// build. That keeps `dicttool build` reproducible from files in the repository: the macOS
/// dictionary decides the list once, a human reviews the diff, and the build behaves the same
/// on any machine. Regenerating is an explicit step — `dicttool undefined`.
enum Undefined {
    static let fileURL = URL(fileURLWithPath: "Sources/dicttool/undefined.txt")

    static func isDefined(_ word: String) -> Bool {
        DCSCopyTextDefinition(nil, word as CFString, CFRangeMake(0, word.utf16.count)) != nil
    }

    /// A missing file means no culling, so a fresh clone still builds a playable lexicon.
    static func load() -> Set<String> {
        guard let text = try? String(contentsOf: fileURL, encoding: .utf8) else { return [] }
        return Set(
            text.split(separator: "\n")
                .map { $0.trimmingCharacters(in: .whitespaces).lowercased() }
                .filter { !$0.isEmpty && !$0.hasPrefix("#") })
    }

    static func regenerate(candidates: [String]) throws {
        var undefined = candidates.filter { !isDefined($0) }
        undefined.sort()

        let header = """
            # Words with no entry in any dictionary installed on the machine that generated this
            # file. Culled from the lexicon: a word no established dictionary defines is one no
            # player will miss, and one the definition bubble could never explain.
            #
            # Generated by `dicttool undefined`, then committed. The build reads this file rather
            # than querying the system dictionary, so `dicttool build` produces the same lexicon
            # on any Mac. Regenerate deliberately and review the diff.
            #
            # \(undefined.count) words.

            """
        try (header + undefined.joined(separator: "\n") + "\n")
            .write(to: fileURL, atomically: true, encoding: .utf8)
        print("wrote \(fileURL.path) — \(undefined.count.formatted()) of \(candidates.count.formatted()) undefined")
    }
}
